
version: '3'

services:
  backend:
      build: 
        context: ./backend
        dockerfile: Dockerfile
      image: addiction-backend
      container_name: addiction-backend
      command: bash -c "python app/server.py"
      ports:
        - 8000:8000
      networks:
        - db-net
  frontend:
      build: 
        context: ./frontend
        dockerfile: Dockerfile
      image: addiction-frontend
      container_name: addiction-frontend
      networks:
        - db-net
  nginx-proxy:
      image: nginx:1.17.10
      container_name: addiction-nginx
      depends_on:
        - backend
        - frontend
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      ports:
        - 80:3000
      networks:
        - db-net

networks:
  db-net:
    driver: bridge
      