version: 2.1

jobs:
  build-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout # pulls code from github repo
      - restore_cache:
          keys: [frontend-build]
      - run:
          name: install & build
          command: |
            cd frontend
            sudo npm install -g'
          - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Build front-end
          command: |
          sudo npm install
          npm run build
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./frontend/node_modules

  build-backend:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build]
      - run:
          name: Back-end build
          command: |
            cd backend
            cd app
            cd requirements
            python -m pip install --upgrade pip
            pip install -r requirements.txt
      - save_cache:
          paths: [backend/dependencies/app]
          key: backend-build

workflows:
  default:
    jobs:
      - build-frontend
      - build-backend
