version: 2.1

jobs:
  build-frontend:
    docker:
      - image: circleci/node:16.10.0
    steps:
      - checkout # pulls code from github repo
      - run:
          name: cd & update
          command: |
            cd frontend
            sudo npm install -g
      - restore_cache:
          key: dependency-cache-{{ checksum "./frontend/package.json" }}
      - run:
          name: Build front-end
          command: |
            cd frontend
            sudo npm install
          # npm run build
      - save_cache:
          key: dependency-cache-{{ checksum "./frontend/package.json" }}
          paths:
            - ./frontend/node_modules
      - run:
          name: Docker
          when: on_success
          command: |
            docker --version
            docker login -u=$DOCKER_LOGIN -p=$DOCKER_PASSWORD
            docker build -t codak77/addictionsupportweb:frontend --build-arg codak77=addictionsupportweb-frontend .
            docker push codak77/addictionsupportweb:frontend
            echo "Docker build made sucessfully!! for addictionsupportweb frontend"
      - run:
          name: Build Failure
          when: on_fail
          command: |
            echo "ERROR building addictionsupportweb:frontend $CIRCLE_BRANCH" 
    
  build-backend:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build]
      - run:
          name: Back-end build
          command: |
            cd backend/app/requirements
            python -m pip install --upgrade pip
            pip install -r requirements.txt
      - save_cache:
          paths: [backend/dependencies/app]
          key: backend-build

      - run:
          name: Docker
          when: on_success
          command: |
            docker --version
            docker login -u=$DOCKER_LOGIN -p=$DOCKER_PASSWORD
            docker build -t codak77/addictionsupportweb:backend --build-arg codak77=addictionsupportweb-backend .
            docker push codak77/addictionsupportweb:backend
            echo "Docker build made sucessfully!! for addictionsupportweb backend"
      - run:
          name: Build Failure
          when: on_fail
          command: |
            echo "ERROR building addictionsupportweb:backend $CIRCLE_BRANCH" 

workflows:
  default:
    jobs:
      - build-frontend
      - build-backend
    
