version: 2.1

jobs:
  build-and-push:
    docker:
      - image: circleci/node:16.10.0
      - image: cimg/python:3.8
      - image: docker:17.09.1-ce-git
    steps:
      - checkout # pulls code from github repo
      - run:
          name: cd & update
          command: |
            cd frontend
            sudo npm install -g
      - restore_cache:
          key: dependency-cache-{{ checksum "./frontend/package.json" }}
      - run:
          name: Build front-end
          command: |
            cd frontend
            sudo npm install
          # npm run build
      - save_cache:
          key: dependency-cache-{{ checksum "./frontend/package.json" }}
          paths:
            - ./frontend/node_modules

      - restore_cache:
          keys: [backend-build]
      - run:
          name: Back-end build
          command: |
            cd backend
            cd app
            cd requirements
            python -m pip install --upgrade pip
            pip install -r requirements.txt
      - save_cache:
          paths: [backend/dependencies/app]
          key: backend-build

      - run:
          name: Docker
          when: on_success
          command: |
            docker --version
            docker login -u=$DOCKER_LOGIN -p=$DOCKER_PASSWORD
            docker build -t codak77/addictionsupportweb:$CIRCLE_BRANCH --build-arg codak77=addictionsupportweb-$CIRCLE_BRANCH .
            docker push codak77/addictionsupportweb:$CIRCLE_BRANCH
            echo "Docker build made sucessfully!! for addictionsupportweb $CIRCLE_BRANCH"
      - run:
          name: Build Failure
          when: on_fail
          command: |
            echo "ERROR building addictionsupportweb $CIRCLE_BRANCH" 

workflows:
  default:
    jobs:
      - build-and-push
